name: Run Cypress tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      # Debug modunu etkinleştirmek için koşul ekleniyor
      - name: Run Cypress tests
        if: github.event_name == 'pull_request' && github.actor == 'myusername'
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          config-file: 'cypress.config.js'
