name: main
on: push
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
        env:
          # pass the Cypress Cloud records key as an environment variable
          CYPRESS_USERNAME: ${{ secrets.MY_EMAIL }}    
          CYPRESS_PASSWORD: ${{ secrets.MY_PASSWORD }}


# name: main
# on: push
# jobs:
#   cypress-run:
#     name: Cypress run
#     runs-on: ubuntu-22.04
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Set up Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: '14'

#       - name: Install dependencies
#         run: npm install

#       - name: Cypress run
#         uses: cypress-io/github-action@v6
#         with:
#           build: npm run build
#           start: npm start
#         env:
#           CYPRESS_USERNAME: ${{ secrets.MY_EMAIL }}
#           CYPRESS_PASSWORD: ${{ secrets.MY_PASSWORD }}



